import './globals.css';
import Image from 'next/image';
import VositaLogo from '../src/app/images/Vosita-Logo.svg';
import FacebookIcon from '../src/app/images/icons/facebook.svg';
import InstagramIcon from '../src/app/images/icons/instagram.svg';
import LinkedInIcon from '../src/app/images/icons/linkedin.svg';
import BlogIcon from '../src/app/images/icons/blog.svg';
import TikTokIcon from '../src/app/images/icons/tiktok.svg';
import XIcon from '../src/app/images/icons/x-twitter.svg';
import YouTubeIcon from '../src/app/images/icons/youtube.svg';
import AppStore from '../src/app/images/appstore.svg';
import GooglePlay from '../src/app/images/googleplay.png';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header className='app-header'>
          <a href='https://vosita.com'>
            <Image src={VositaLogo} width={160} alt='logo' />
          </a>
          <div className='nav-links'>
            <a className='demo-link' href='https://vosita.com/request-demo'>
              <p>Schedule a demo</p>
            </a>
            <a className='login-link' href='https://vosita.com/account'>
              <p>Login / Register</p>
            </a>
          </div>
        </header>
        {children}
        <footer>
          <div className='footer-container'>
            <div className='footer-column'>
              <h3>Explore</h3>
              <ul>
                <li>
                  <a href='#'>List your practice on Vosita</a>
                </li>
                <li>
                  <a href='#'>Request a demo</a>
                </li>
                <li>
                  <a href='#'>Pricing</a>
                </li>
                <li>
                  <a href='#'>Privacy Policy</a>
                </li>
                <li>
                  <a href='#'>About Us</a>
                </li>
                <li>
                  <a href='#'>Request BAA</a>
                </li>
                <li>
                  <a href='#'>Terms & Conditions</a>
                </li>
              </ul>
            </div>
            <div className='footer-column'>
              <h3>Top Specialties</h3>
              <ul>
                <li>
                  <a href='#'>Dermatologist</a>
                </li>
                <li>
                  <a href='#'>Family Physician</a>
                </li>
                <li>
                  <a href='#'>Internist</a>
                </li>
                <li>
                  <a href='#'>OB-GYN</a>
                </li>
                <li>
                  <a href='#'>Pain Management Specialist</a>
                </li>
                <li>
                  <a href='#'>Pediatrician</a>
                </li>
                <li>
                  <a href='#'>Physiatrist</a>
                </li>
              </ul>
            </div>
            <div className='footer-column'>
              <h3></h3>
              <ul>
                <li>
                  <a href='#'>Podiatrist (Foot & Ankle specialist)</a>
                </li>
                <li>
                  <a href='#'>Primary Care Physician</a>
                </li>
                <li>
                  <a href='#'>Pulmonologist</a>
                </li>
                <li>
                  <a href='#'>Sleep Medicine Specialist</a>
                </li>
                <li>
                  <a href='#'>View all</a>
                </li>
              </ul>
            </div>
            <div className='footer-info'>
              <Image src={VositaLogo} alt='Vosita Logo' className='logo' />
              <address>
                1 Kalisa Way, Suite 101, Paramus, NJ 07652, USA
                <br />
                <a href='tel:+12019037000'>(201) 903-7000</a>
                <br />
                <a href='mailto:info@vosita.com'>info@vosita.com</a>
              </address>
              <div className='social-icons'>
                <a href='#'>
                  <Image src={FacebookIcon} alt='Facebook' />
                </a>
                <a href='#'>
                  <Image src={XIcon} alt='Twitter' />
                </a>
                <a href='#'>
                  <Image src={InstagramIcon} alt='Instagram' />
                </a>
                <a href='#'>
                  <Image src={LinkedInIcon} alt='LinkedIn' />
                </a>
                <a href='#'>
                  <Image src={YouTubeIcon} alt='YouTube' />
                </a>
                <a href='#'>
                  <Image src={TikTokIcon} alt='TikTok' />
                </a>
                <a href='#'>
                  <Image src={BlogIcon} alt='Blog' />
                </a>
              </div>
              <div className='app-buttons'>
                <a href='#'>
                  <Image width={200} src={AppStore} alt='App Store' />
                </a>
                <a href='#'>
                  <Image width={200} src={GooglePlay} alt='Google Play' />
                </a>
              </div>
            </div>
          </div>
          <div className='footer-bottom'>
            <p>
              &copy; 2024 | Vosita Healthcare Inc. | All rights reserved. |
              v2.7.2
            </p>
            <a href='#'>Sitemap</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
